---
title: "Fire Counts Distribution"
author: "Leonardo A. Saravia"
date: "4/6/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read fires from model
 
```{r readpng, echo=T,message=F,warning=T,eval=TRUE}
require(future.apply)
require(lubridate)
require(tidyverse)
require(Matrix)
require(spatialwarnings)
require(gtools)
source("R/functions.r")

# Initialize data.frame
patch_df <- tibble()

#
# Density .9 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.9.*2\\.0E-7.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)

df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))


#
# Density .8 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.8.*2\\.0E-7.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)

df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))
#file.remove(paste0("Data/",fire_bricks))

#
# Density .7 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.7.*2\\.0E-7.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)

df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))
#
# Density .6 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.6.*2\\.0E-7.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))
#file.remove(paste0("Data/",fire_bricks))

#
# Density .5 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.5.*2\\.0E-7.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))
#file.remove(paste0("Data/",fire_bricks))

patch_df %>% filter(initial_forest_density==0.4,fire_probability==2e-7,size==63001) %>% select(days,npatches,tot_patch)

#
# Density .4 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.4.*2\\.0E-7.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))
#file.remove(paste0("Data/",fire_bricks))

patch_df %>% filter(initial_forest_density==0.4,fire_probability==2e-7,size==63001) %>% select(days,npatches,tot_patch)

#
# Density .3 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.3.*2\\.0E-7.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))
#file.remove(paste0("Data/",fire_bricks))

patch_df %>% filter(initial_forest_density==0.4,fire_probability==2e-7,size==63001) %>% select(days,npatches,tot_patch)


#
# Density .8 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.8.*2\\.0E-7.*500\\.txt$")
fire_bricks <- mixedsort(fire_bricks)

df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))

# patch_df <- patch_df %>% filter(!(initial_forest_density==0.8 & fire_probability==2e-7 & size==250000)) 

patch_df %>% filter(initial_forest_density==0.8,fire_probability==2e-7,size==250000) %>% select(days,npatches,tot_patch)
file.remove(paste0("Data/",fire_bricks))

#
# Density .7 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.7.*2\\.0E-7.*500\\.txt$")
fire_bricks <- mixedsort(fire_bricks)

df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))


#
# Density .6 Probability of Fire 2.0E-7 regrowth interval 2160 days 500 x 500
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.6.*2\\.0E-7.*500\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))
file.remove(paste0("Data/",fire_bricks))

#
# Density .4 Probability of Fire 2.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.4.*2\\.0E-7.*500\\.txt$")
fire_bricks <- mixedsort(fire_bricks)

df <- extract_patch_distr_nl(fire_bricks)

patch_df <- bind_rows(patch_df, df %>% arrange(days))
#patch_df <- patch_df %>% filter(!(initial_forest_density==0.4 & fire_probability==2e-7 & size==250000)) 

patch_df %>% filter(initial_forest_density==0.4,fire_probability==2e-7,size==250000) %>% select(days,npatches,tot_patch)
file.remove(paste0("Data/",fire_bricks))

rm(df)
save.image()

#
# Density .8 Probability of Fire 1.0E-6 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.8.*1\\.0E-6.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))

fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.8.*1\\.0E-6.*500\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))



#
# Density .6 Probability of Fire 1.0E-6 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.6.*1\\.0E-6.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))

fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.6.*1\\.0E-6.*500\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))


#
# Density .4 Probability of Fire 1.0E-6 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.4.*1\\.0E-6.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))

fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.4.*1\\.0E-6.*500\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))



#
# Density .8 Probability of Fire 1.0E-7 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.8.*1\\.0E-7.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))

fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.8.*1\\.0E-7.*500\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))

#
# Density .8 Probability of Fire 1.0E-5 regrowth interval 2160 days
#
fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.8.*1\\.0E-5.*251\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))

fire_bricks <- list.files(path="Data",pattern="^Fire_0\\.8.*1\\.0E-5.*500\\.txt$")
fire_bricks <- mixedsort(fire_bricks)
df <- extract_patch_distr_nl(fire_bricks)
patch_df <- bind_rows(patch_df, df %>% arrange(days))



rm(df)
save.image()
```

# Plot Fires 
 
```{r plotFires, echo=T,message=F,warning=T,eval=TRUE}
require(tidyverse)
names(patch_df) 
patch_df %>% count(initial_forest_density,fire_probability,size) %>% mutate(scaled_fire_probability = fire_probability/size)

patch_pl <- patch_df %>% filter(type=="pl") %>% mutate(date=ymd("1990-01-01")+days, max_patch=max_patch/size,tot_patch=tot_patch/size, npatches = npatches/size) 
patch_pl <- bind_rows(patch_pl, patch_df %>% filter(is.na(type)) %>% mutate(date=ymd("1990-01-01")+days,
                                                                            max_patch=max_patch/size,tot_patch=tot_patch/size, npatches = npatches/size) )

save.image()

patch_pl %>% filter(size==250000) %>% 
ggplot(  aes(date,max_patch, color=factor(initial_forest_density))) + geom_line() + theme_bw() +
      scale_color_viridis_d(name="Density")  + 
      ylab("Max Patch Size") +  
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) + facet_grid(fire_probability~size)

patch_pl %>% filter(size==250000) %>% 
ggplot( aes(date,tot_patch, color=factor(initial_forest_density))) + geom_line() + theme_bw() +
      scale_color_viridis_d(name="Density")  + 
      ylab("Total Patch Size") +  
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) + facet_grid(fire_probability~size)

patch_pl %>% filter(size==250000) %>% 
ggplot(  aes(date,npatches, color=factor(initial_forest_density))) + geom_line() + theme_bw() +
      scale_color_viridis_d(name="Density")  + 
      ylab("Number of Patches") +  scale_y_log10() +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+ facet_grid(fire_probability~size)


patch_pl %>% filter(size==63001) %>% 
ggplot(  aes(date,max_patch, color=factor(initial_forest_density))) + geom_line() + theme_bw() +
      scale_color_viridis_d(name="Density")  + 
      ylab("Max Patch Size") +  
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) + facet_grid(fire_probability~size)

patch_pl %>% filter(size==63001) %>% 
ggplot( aes(date,tot_patch, color=factor(initial_forest_density))) + geom_line() + theme_bw() +
      scale_color_viridis_d(name="Density")  + 
      ylab("Total Patch Size") +  
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) + facet_grid(fire_probability~size)

patch_pl %>% filter(size==63001) %>% 
ggplot(  aes(date,npatches, color=factor(initial_forest_density))) + geom_line() + theme_bw() +
      scale_color_viridis_d(name="Density")  + 
      ylab("Number of Patches") +  
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+ facet_grid(fire_probability~size)


#require(ggrepel)
#mutate( label =ifelse(date>="2019-11-01" & date<"2020-02-01",as.character(date),"")) %>%

patch_pl %>% filter(size==250000,fire_probability!=1e-07) %>% 
ggplot(  aes(npatches,tot_patch,color=factor(initial_forest_density) ))+ geom_point(alpha=0.6) + theme_bw() +
      scale_color_viridis_d(guide=FALSE)  + 
      xlab("Number of Patches") +  
      ylab("Total Size (ha)") +  
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) + facet_grid(fire_probability~size) 
    # + geom_label_repel(label=as.character(date)) 

ggsave("Figures/mdl_NumberVsSize_d06-08-pf2e-07.jpg",width=8,height=6,units="in",dpi=600)

#
# Density 0.8 by Fire-Probability 
#
patch_pl %>% filter(size==63001,initial_forest_density==0.8) %>% 
ggplot(  aes(npatches,tot_patch,color=factor(fire_probability)))+ geom_point(alpha=0.6) + theme_bw() +
      scale_color_viridis_d(name="Fire\nProb.")  + 
      xlab("Number of Patches") +  
      ylab("Total Size (%)") +  
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
    # + geom_label_repel(label=as.character(date)) 

ggsave("Figures/mdl_NumberVsSize_Dens08_FireProb.jpg",width=8,height=6,units="in",dpi=600)


patch_pl %>% filter(size==63001,fire_probability==2e-07) %>% group_by(initial_forest_density,year(date)) %>% summarise(tot_patch=sum(tot_patch)) %>%
ggplot( aes(initial_forest_density,tot_patch)) + geom_point() + theme_bw() +
      scale_color_viridis_d()  + 
      ylab("Burned Size by month") +  xlab("Density")
#      theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

ggsave("Figures/mdl_DensityVsPatchSize_FireProb2e-07.jpg",width=4,height=4,units="in",dpi=600)


patch_pl %>% filter(size==63001,initial_forest_density==0.8) %>% 
ggplot( aes(date,tot_patch, color=factor(fire_probability))) + geom_line() + theme_bw() +
      scale_color_viridis_d(name="Fire\nProb")  + 
      ylab("Total Patch Size") +  
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
ggsave("Figures/mdl_PatchSizeVsTime_Density08.jpg",width=8,height=6,units="in",dpi=600)


```
